// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoApi.Models;

namespace ProjetoApi.Migrations
{
    [DbContext(typeof(AvisoUrgenteContext))]
    partial class AvisoUrgenteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("ProjetoApi.Models.ProcessoMovimentacoes", b =>
                {
                    b.Property<int>("ProcessoMovimentacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("ProcessoMovimentacaoId");

                    b.HasIndex("NumeroProcesso");

                    b.ToTable("ProcessoMovimentacoes");
                });

            modelBuilder.Entity("ProjetoApi.Models.Processos", b =>
                {
                    b.Property<string>("NumeroProcesso")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<int>("Grau")
                        .HasColumnType("INTEGER");

                    b.HasKey("NumeroProcesso");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("ProjetoApi.Models.ProcessoMovimentacoes", b =>
                {
                    b.HasOne("ProjetoApi.Models.Processos", "NumeroProcessoNavigation")
                        .WithMany("ProcessoMovimentacoes")
                        .HasForeignKey("NumeroProcesso")
                        .HasConstraintName("FK_ProcessoMovimentacoes_Processos")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
